# Generated by Django 4.2.7 on 2026-06-09 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=500)),
                ('format', models.CharField(choices=[('ppt', 'PowerPoint'), ('word', 'Word Document')], max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('template_file', models.FileField(blank=True, upload_to='templates/')),
                ('watermarked_file', models.FileField(blank=True, upload_to='watermarked/')),
                ('clean_file', models.FileField(blank=True, upload_to='clean/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
